### PR TITLE
[Date] [Datetime] [Timestamp] Handle `QUARTER`, `WEEK(DAY)`, `ISOWEEK`

### LINKED ISSUE #193: `WEEK(<WEEKDAY>)` unsupported for `LAST_DAY()`, `EXTRACT()`, `DATE_DIFF()`, `DATE_TRUNC()`

### LINKED ISSUE #194: `DATE_DIFF(..., ..., WEEK)` returns incorrect value for multi-year durations
```sql
SELECT DATE_DIFF(DATE "2024-03-26", DATE "2022-03-26", WEEK);
```

Expected: 105
Actual: 1

### LINKED ISSUE #202: Full range of dates not supported
Similar to https://github.com/goccy/go-zetasqlite/pull/133

```
SELECT DATE '0001-01-01', DATE '9999-12-31'
```

### PR DESCRIPTION
**Pull request by ohaibbq**
A number of bugfixes here!

- Full range of dates `0001-01-01` - `9999-12-31` now supported. Previously `dateValueFromLiteral` hit `int64` caps due to the `time.Hour` multiplication occurring before we divided it by `time.Second`.
- `QUARTER` support for `DATE_ADD`
- `WEEK`, `WEEK(DAY OF WEEK)` support for `DATE_DIFF`, `DATE_TRUNC`
- `ISOWEEK`, `ISOYEAR`, `QUARTER` support for `DATE_TRUNC`

Most date function logic has been de-duplicated and now `DATETIME` and `TIMESTAMP` functions defer to `DATE` methods for date parts at the day level or higher. 

Closes #202 
Closes #194
Closes #193

### CODE REVIEW

File: internal/function_date.go [hunk 1]
```diff
@@ -83,38 +87,149 @@ func DATE_SUB(t time.Time, v int64, part string) (Value, error) {
...
+
+		// Manually calculate the number of days based off Unix seconds
+		// time.Time.Sub returns "Infinite" max duration for the case of 9999-12-31.Sub(0001-01-01)
+		// The maximum time.Duration is ~290 years due to being represented in int64 nanosecond resolution
+		days := (end.Unix() - start.Unix()) / 24 / 60 / 60
+		// Calculate number of complete weeks between start and end
+		fullWeeks := days / 7
+		remainder := days % 7
+
+		counts := make([]int64, 7)
```
Comment (goccy) [inline internal/function_date.go:126]: nits: How about using array ? `dayOfWeek := [7]int64{}`

**Comment by goccy** [comment]
Thank you for your contribution ! Please fix lint error 🙏

**Comment by goccy** [comment]
LGTM 👍
