### PR TITLE
fix scalar subquery expression parentheses

### LINKED ISSUE #34: failed to query scalar subquery expression
```sql
SELECT (SELECT 1)
```

is valid SQL on BigQuery as [documented](https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql#subqueries_in_more_places)

image

but it failed on `go-zetasqlite`

```
failed to query SELECT SELECT 1 AS `$col1#1`  AS `$col1#2` : near "SELECT": syntax error
```
----

`formattedQuery` :

```sql
SELECT SELECT 1 AS `$col1#1`  AS `$col1#2` 
```

`stmtNode.DebugString()` :

```
QueryStmt
+-output_column_list=
| +-$query.$col1#2 AS `$col1` [INT64]
+-query=
  +-ProjectScan
    +-parse_location=0-17
    +-column_list=[$query.$col1#2]
    +-expr_list=
    | +-$col1#2 :=
    |   +-SubqueryExpr
    |     +-parse_location=7-17
    |     +-type=INT64
    |     +-subquery_type=SCALAR
    |     +-subquery=
    |       +-ProjectScan
    |         +-parse_location=8-16
    |         +-column_list=[$expr_subquery.$col1#1]
    |         +-expr_list=
    |         | +-$col1#1 := Literal(parse_location=15-16, type=INT64, value=1)
    |         +-input_scan=
    |           +-SingleRowScan
    +-input_scan=
      +-SingleRowScan
```

`go-zetasqlite` : 0.8.3

----

Similarly,

```sql
SELECT ABS((SELECT 1)) -- in function arguments
SELECT * FROM UNNEST([1, 2, 3]) AS val WHERE val = (SELECT 1) -- in WHERE clause
SELECT * FROM UNNEST([1, 2, 3]) AS val GROUP BY val HAVING val = (SELECT 1) -- in HAVING clause
```

also failed as

```
failed to query SELECT zetasqlite_abs(SELECT 1 AS `$col1#1` ) AS `$col1#2` : near "SELECT": syntax error
failed to query SELECT `val#1` FROM (SELECT json_each.value AS `val#1` FROM json_each(zetasqlite_decode_array("eyJoZWFkZXIiOiJhcnJheSIsImJvZHkiOiJbMSwyLDNdIn0=")) WHERE zetasqlite_equal(`val#1`,SELECT 1 AS `$col1#2` )): near "SELECT": syntax error
failed to query SELECT `val#2` FROM (SELECT `val#1` AS `val#2` FROM (SELECT json_each.value AS `val#1` FROM json_each(zetasqlite_decode_array("eyJoZWFkZXIiOiJhcnJheSIsImJvZHkiOiJbMSwyLDNdIn0="))) GROUP BY zetasqlite_group_by(`val#2`) HAVING zetasqlite_equal(`val#2`,SELECT 1 AS `$col1#3` )): near "SELECT": syntax error
```

### PR DESCRIPTION
**Pull request by yokomotod**
fix #34 

Hi. I've found that some kinds of subquery expressions cause errors, so I've tried to fix it.

It seems that `SubqueryExpr(subquery_type=SCALAR)` must be enclosed in parentheses. (I'm fairly new to ZetaSQL and go-zetasqlite so not 100% sure though)

----

:red_square: red status before fix with added tests

```
$ CXX=clang++ go test -run TestQuery/subquery_expr -v
=== RUN   TestQuery
=== RUN   TestQuery/subquery_expr_type_scalar
    query_test.go:3251: failed to query SELECT SELECT 1 AS `$col1#1`  AS `$col1#2` : near "SELECT": syntax error
=== RUN   TestQuery/subquery_expr_type_array
=== RUN   TestQuery/subquery_expr_type_in
=== RUN   TestQuery/subquery_expr_type_exists
--- FAIL: TestQuery (0.01s)
    --- FAIL: TestQuery/subquery_expr_type_scalar (0.00s)
    --- PASS: TestQuery/subquery_expr_type_array (0.00s)
    --- PASS: TestQuery/subquery_expr_type_in (0.00s)
    --- PASS: TestQuery/subquery_expr_type_exists (0.00s)
FAIL
exit status 1
FAIL	github.com/goccy/go-zetasqlite	0.026s
```

### CODE REVIEW

File: query_test.go [hunk 1]
```diff
@@ -3220,6 +3220,28 @@ FROM
 				{"false", "boolean"},
 			},
 		},
+
+		// subquery expr
+		{
+			name:         "subquery_expr_type_scalar",
+			query:        "SELECT (SELECT 1)",
```
Comment (yokomotod) [inline query_test.go:3227]: It does not matter whether the subquery is in the SELECT/WHERE/HAVING clause etc., the scalar type seems to be the problem.

Would you like to add these test cases?

```sql
SELECT * FROM UNNEST([1, 2, 3]) AS val WHERE val = (SELECT 1)
SELECT * FROM UNNEST([1, 2, 3]) AS val GROUP BY val HAVING val = (SELECT 1)
SELECT ABS((SELECT 1))
```

File: internal/formatter.go [hunk 2]
```diff
@@ -541,6 +541,7 @@ func (n *SubqueryExprNode) FormatSQL(ctx context.Context) (string, error) {
 	}
 	switch n.node.SubqueryType() {
 	case ast.SubqueryTypeScalar:
+		return fmt.Sprintf("(%s)", sql), nil
```
Comment (yokomotod) [inline internal/formatter.go:544]: I'm not sure about  `case ast.SubqueryTypeLikeAny:` and `case ast.SubqueryTypeLikeAll:`.

But it seems all types of Scalar/Array/Exists/In require parentheses in the end, so it is possible that LikeAny/LikeAll need to be enclosed as well...?

File: query_test.go (hunk 1 above)
Comment (goccy) [reply query_test.go:3227]: Please add them !

File: internal/formatter.go (hunk 2 above)
Comment (goccy) [reply internal/formatter.go:544]: Perhaps the parenthesis are needed. If you can add a test case for them, please do.

File: query_test.go (hunk 1 above)
Comment (yokomotod) [reply query_test.go]: added.

File: internal/formatter.go (hunk 2 above)
Comment (yokomotod) [reply internal/formatter.go]: @goccy I added parenthesis to them, but I DID NOT add test cases. [diff](https://github.com/goccy/go-zetasqlite/pull/35/files#diff-0102133126f709542bd93e0b83ea950894fc4ecd89993fe348751b1f8403b38fL561)

:point_down: This is how it happend.

I found that ZetaSQL seems to have extended language feature like `WHERE val LIKE ANY ("abc")` / `WHERE val ALL ANY ("abc")`

https://github.com/google/zetasql/blob/177d495a064e38684c462cf883e22428273bd996/zetasql/public/options.proto#L816
https://github.com/google/zetasql/blob/57651f4f0cf9efa76163bc0282edfcf98dd72414/zetasql/analyzer/testdata/hints.test#L2136

However, they are not enabled in BigQuery.

image

image

Our test also failed if we add `SELECT "abcd" LIKE ANY (SELECT "a%d")`.

```
failed to parse statements: failed to parse statement: INVALID_ARGUMENT: LIKE ANY is not supported [type.googleapis.com/zetasql.ErrorLocation='\x08\x01\x10\x14']
```

So for now we can't add such test, and `ast.SubqueryTypeLikeAny:` case will never be reached.

Does that sound good?

Comment (goccy) [reply internal/formatter.go]: ZetaSQL's Analyzer allows you to optionally specify which features to support. https://github.com/goccy/go-zetasqlite/blob/46f8b1037933aa6742331940b99e64cb531790c8/internal/analyzer.go#L49-L81

The following is the option in this case, which I think can be tested by enabling it.

https://github.com/goccy/go-zetasql/blob/50b559cf1db2019fd273c97a5338a3e4f1424952/enum.go#L666

File: query_test.go [hunk 3]
```diff
@@ -3220,6 +3220,43 @@ FROM
 				{"false", "boolean"},
 			},
 		},
+
+		// subquery expr
+		{
+			name:         "SubqueryExpr(subquery_type=SCALAR) at SELECT",
```
Comment (goccy) [inline query_test.go:3226]: I want to express `name` parameter without using symbols such as `()=` .
e.g.) `subquery expression with scalar type at SELECT`

Comment (yokomotod) [reply query_test.go]: ok, fixed!

File: internal/formatter.go (hunk 2 above)
Comment (yokomotod) [reply internal/formatter.go]: @goccy 

Just a quick report.

Test case:

```go
		{
			name:         "subquery expr with like any type",
			query:        `SELECT "abc" LIKE ANY ("ab%", "xy%")`,
			expectedRows: [][]interface{}{{true}},
		},
		{
			name:         "subquery expr with like some type",
			query:        `SELECT "abc" LIKE SOME ("ab%", "xy%")`,
			expectedRows: [][]interface{}{{true}},
		},
		{
			name:         "subquery expr with like all type",
			query:        `SELECT "abc" LIKE ALL ("a%", "ab%")`,
			expectedRows: [][]interface{}{{true}},
		},
```

Without `zetasql.FeatureV13LikeAnySomeAll` language feature:

```
--- FAIL: TestQuery (0.01s)
    --- FAIL: TestQuery/subquery_expr_with_like_any_type (0.00s)
        query_test.go:3281: failed to parse statements: failed to parse statement: INVALID_ARGUMENT: LIKE ANY is not supported [type.googleapis.com/zetasql.ErrorLocation='\x08\x01\x10\x13']
    --- FAIL: TestQuery/subquery_expr_with_like_some_type (0.00s)
        query_test.go:3281: failed to parse statements: failed to parse statement: INVALID_ARGUMENT: LIKE SOME is not supported [type.googleapis.com/zetasql.ErrorLocation='\x08\x01\x10\x13']
    --- FAIL: TestQuery/subquery_expr_with_like_all_type (0.00s)
        query_test.go:3281: failed to parse statements: failed to parse statement: INVALID_ARGUMENT: LIKE ALL is not supported [type.googleapis.com/zetasql.ErrorLocation='\x08\x01\x10\x13']
FAIL

```

With `zetasql.FeatureV13LikeAnySomeAll`, `INVALID_ARGUMENT: LIKE ANY is not supported ` error has gone but then another error:

```
--- FAIL: TestQuery (0.01s)
    --- FAIL: TestQuery/subquery_expr_with_like_any_type (0.00s)
        query_test.go:3281: failed to query SELECT zetasqlite_like_any("eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoiYWJjIn0=","eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoiYWIlIn0=","eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoieHklIn0=") AS `$col1#1` : no such function: zetasqlite_like_any
    --- FAIL: TestQuery/subquery_expr_with_like_some_type (0.00s)
        query_test.go:3281: failed to query SELECT zetasqlite_like_any("eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoiYWJjIn0=","eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoiYWIlIn0=","eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoieHklIn0=") AS `$col1#1` : no such function: zetasqlite_like_any
    --- FAIL: TestQuery/subquery_expr_with_like_all_type (0.00s)
        query_test.go:3281: failed to query SELECT zetasqlite_like_all("eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoiYWJjIn0=","eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoiYSUifQ==","eyJoZWFkZXIiOiJzdHJpbmciLCJib2R5IjoiYWIlIn0=") AS `$col1#1` : no such function: zetasqlite_like_all
FAIL
```

It seems that currently zetasqlite couldn't support `LIKE ANY` clauses and need to support them first.  
I can try to implement it but we should separate to another PR, I think ?

On the other hand, I'm not sure the priority of those supports because the real BigQuery doesn't support them neither.

Comment (goccy) [reply internal/formatter.go]: I see. Thank you for confirmation ! You don't need to add test cases for `ANY` and `ALL` .
I will support them later

**Comment by goccy** [comment]
LGTM ! Thank you for your contribution !
