### PR TITLE
[Date] Implement `%p`, improve token composition, fix leading-space parsers/formatters, improve error messages, slurp whitespace

### LINKED ISSUE #151: [Date] `%p` token not implemented

### LINKED ISSUE #165: [Date] Dates with single digit preceded by space cannot be parsed
The `%e` `%k` and `%l` elements expect a leading space when the value is a single digit; but also permit a leading space for 2 digit numbers when available.

Formatters also do not currently include the leading space.

```go
{
	name:         "parse timestamp with %k",
	query:        `SELECT PARSE_TIMESTAMP("%k", " 9");`,
	expectedRows: [][]interface{}{{createTimestampFormatFromString("1970-01-01 09:00:00+00")}},
},
{
	name:         "parse timestamp with %k",
	query:        `SELECT PARSE_TIMESTAMP("%k", " 9");`,
	expectedRows: [][]interface{}{{createTimestampFormatFromString("1970-01-01 09:00:00+00")}},
},
{name: "parse_timestamp with %D",
	query:        `SELECT PARSE_TIMESTAMP("%D", "02/02/99");`,
	expectedRows: [][]interface{}{{createTimestampFormatFromString("1999-02-02 00:00:00+00")}},
},
{
	name:  "parse timestamp with %p",
	query: `SELECT PARSE_TIMESTAMP("%I%p", "9am"), PARSE_TIMESTAMP("%I%p", "12am"), PARSE_TIMESTAMP("%l%p", " 2am"), PARSE_TIMESTAMP("%I%p", "10PM");`,
	expectedRows: [][]interface{}{{
		createTimestampFormatFromString("1970-01-01 09:00:00+00"),
		createTimestampFormatFromString("1970-01-01 00:00:00+00"),
		createTimestampFormatFromString("1970-01-01 02:00:00+00"),
		createTimestampFormatFromString("1970-01-01 22:00:00+00"),
	}},
},
```

### LINKED ISSUE #167: [Dates] Improve time parser's handling of whitespace
In BigQuery, the parser eats all whitespace characters from the target when it encounters a space in the format token.

These strings should parse:
```sql
SELECT
  -- one space in format string; many spaces in target
  PARSE_DATETIME("%m/%d/%Y %I:%M:%S%p", "12/16/2022        12:00:00AM")
```

### Actual
```
could not parse hour number: leading character is not a digit
```

### PR DESCRIPTION
**Pull request by ohaibbq**
Closes #165 
Closes #151 
Closes #167

### CODE REVIEW

File: internal/function_time_parser.go [hunk 1]
```diff
@@ -863,7 +869,58 @@ func smallAMPMFormatter(t *time.Time) ([]rune, error) {
...
+	return progress, nil
+}
+
+func ampmPostProcessor(text []rune, t *time.Time) {
+	morning := strings.ToLower(string(text)) == "am"
+	hour := t.Hour()
+	if hour == 12 && morning {
+		hour = 0
+	}
+	if !morning {
```
Comment (ohaibbq) [inline internal/function_time_parser.go:891]: update case of 12pm turning into 24

**Comment by goccy** [comment]
Please fix the error from linter

**Review by goccy — APPROVED** [review]
Thank you for your awesome PR !!! LGTM 👍
