### PR TITLE
[Filter] Fix syntax error that occurred for some queries using subselects or QUALIFY

### LINKED ISSUE #147: [Formatter] Filtering sub-selects causes syntax error
```sql
WITH contributors AS (SELECT 'Dan' AS name, 3 AS tenure),
toks AS (
    SELECT name FROM (
        SELECT * FROM contributors
        WHERE name = 'Dan'
    ) sub
    WHERE tenure = 3
)
SELECT * FROM toks;
```

raises

```
failed to query ...: near "WHERE": syntax error
--- FAIL: TestQuery (0.02s)
    --- FAIL: TestQuery/syntax_error_test (0.01s)
```

Adjusting the query to not use a filter in the sub-select parses and runs successfully i.e.

```sql
WITH contributors AS (SELECT 'Dan' AS name, 3 AS tenure),
toks AS (
    SELECT name FROM (
        SELECT * FROM contributors
    ) sub
    WHERE tenure = 3
)
SELECT * FROM toks;
```

### LINKED ISSUE #150: [Filter] `QUALIFY` clause on a `SELECT ... GROUP BY` raises syntax error
Related to #147

```sql
WITH produce AS (
	SELECT 'kale' AS item, 23 AS purchases
)
SELECT item, sum(purchases)
FROM produce
GROUP BY item
QUALIFY ROW_NUMBER() OVER (PARTITION BY item ORDER BY item) = 1
```

### Expected
| item | col1 |
| -- | -- |
| kale | 23 |

### Actual

```
failed to query ...: near "WHERE": syntax error
```

### PR DESCRIPTION
**Pull request by ohaibbq**
This also reduces the number of sub-selects that are necessary to aid cases which result in #153 

Closes #147 
Closes #150

### CODE REVIEW

File: internal/formatter.go [hunk 1]
```diff
@@ -686,7 +687,10 @@ func (n *ColumnHolderNode) FormatSQL(ctx context.Context) (string, error) {
 	return "", nil
 }
 
+var tokensAfterFromClause = [...]string{"WHERE", "GROUP BY", "HAVING", "QUALIFY", "WINDOW", "ORDER BY", "COLLATE"}
+
 func (n *FilterScanNode) FormatSQL(ctx context.Context) (string, error) {
+	removeExpressions := regexp.MustCompile(`\(.+?\)`)
```
Comment (goccy) [inline internal/formatter.go:693]: This process is able to cache like the follows
```
var removeExpressions = regexp.MustCompile(`\(.+?\)`)

func (n *FilterScanNode) FormatSQL(ctx context.Context) (string, error) {
...
}
```

**Comment by goccy** [comment]
LGTM 👍
